# Taps
tap "brewsci/science"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/science"
tap "homebrew/versions"

# 중요! 이 줄이 없으면, ~/Applications에 설치하므로 꼭 넣어야 한다.
cask_args appdir: "/Applications"

# Binaries/Libraries
brew "automake"
brew "cmake"
brew "coreutils"
brew "gcc@4.9"
brew "gettext"
brew "git"
brew "libyaml"
brew "nvm"
brew "openssl@1.1"
brew "pyenv"
brew "rbenv"
brew "sshpass"
brew "wget"
brew "watchman"
brew "yarn", args: ["without-node"]
brew "zsh"

# Applications
cask "alfred"
cask "google-chrome"
cask "iterm2"
cask "postman"
cask "vagrant"
cask "virtualbox"
