---

- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local environment
  hosts: local
  roles:
    - git
    - { role: package_manager, tags: ['bootstrap'] }
    - { role: zsh, tags: ['bootstrap'] }
    - vim
    - ros
